CREATE TABLE book (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    category ENUM('Book', 'Comics', 'Manga', 'Mhanwa') NOT NULL,
    literary_genre ENUM(
        'Fantasy', 
        'Science Fiction', 
        'Mystery', 
        'Thriller', 
        'Romance', 
        'Historical', 
        'Horror', 
        'Dystopian', 
        'Contemporary Fiction', 
        'Action & Adventure', 
        'Graphic Novel', 
        'Poetry', 
        'Satire', 
        'Biography', 
        'Autobiography', 
        'Memoir', 
        'History', 
        'True Crime', 
        'Self-Help', 
        'Philosophy', 
        'Science & Technology', 
        'Religion & Spirituality', 
        'Business & Economics', 
        'Politics & Social Sciences', 
        'Health & Wellness', 
        'Psychological'
    ) NOT NULL,
    language ENUM('Italiano', 'English') NOT NULL,
    isread TINYINT(1) NOT NULL DEFAULT 0,
    description TEXT,
    image VARCHAR(255),
    date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);